fix: fix `plugins/fs` infinite loop on autoregen
tauri-apps/plugins-workspace pull request #1029
Opened 2024-03-05 13:31 UTC by otamam818

The auto-regen from `plugins/fs/build.rs` would keep generating on compile time. Upon check-up, it made more sense to just make sure it doesn't regenerate files redundantly, so I implemented a check to see if the files are redundant or not.

Please let me know if I missed something

2024-03-05 13:51 UTC, FabianLars commented
Thanks for contributing!

To merge this we'll need a changefile similar to https://github.com/tauri-apps/plugins-workspace/blob/v2/.changes/fix-zbus-import.md

Also, the if statement is a bit incorrect. As it is, it won't write the file if it doesn't exist already.

2024-03-06 02:32 UTC, otamam818 commented
> Also, the if statement is a bit incorrect. As it is, it won't write the file if it doesn't exist already.

Thanks @FabianLars for pointing that out, I appreciate it. I see it now. Give me a moment, I'll update this PR and address that

> To merge this we'll need a changefile similar to https://github.com/tauri-apps/plugins-workspace/blob/v2/.changes/fix-zbus-import.md

I'll also add a file to `.changes` called `file-autogen-fix.md`

2024-03-06 16:48 UTC, lucasfernog requested changes
this is the way we handle this on the tauri side

2024-03-06 16:48 UTC, lucasfernog commented on plugins/fs/build.rs
> +        }
```suggestion
        let permission_path = base_dirs.join(format!("{lower}.toml"));
        if toml != std::fs::read_to_string(&permission_path).unwrap_or_default() {
            std::fs::write(permission_path, toml)
                .unwrap_or_else(|e| panic!("unable to autogenerate ${lower}: {e}"));
        }
```

2024-03-06 17:18 UTC, amrbashir approved these changes

2024-03-06 17:30 UTC, merged