feat(window-state): add option to use json
tauri-apps/plugins-workspace pull request #1078
Opened 2024-03-15 11:55 UTC by thewh1teagle

2024-03-28 02:34 UTC, amrbashir requested changes
sorry for the very late reply, I think we should just use json only and remove bincode

2024-03-28 17:38 UTC, thewh1teagle commented
> sorry for the very late reply, I think we should just use json only and remove bincode

I think so too, just need to check that it's not a breaking change (what happens if the plugin can't read the old bincode file)
Also I think that it will be good to serialize it with indentation (pretty and readable)

2024-03-29 00:25 UTC, amrbashir approved these changes, later dismissed

2024-03-29 00:41 UTC, amrbashir approved these changes
Thank you

2024-03-29 00:41 UTC, merged