refactor(geolocation): simplify API, defer permission checks
tauri-apps/plugins-workspace pull request #1773
Opened 2024-09-13 12:08 UTC by lucasfernog

2024-09-13 12:09 UTC, lucasfernog commented
Closes #1631

2024-09-13 13:15 UTC, amrbashir approved these changes, later dismissed

2024-09-16 13:13 UTC, amrbashir requested changes

2024-09-16 13:13 UTC, amrbashir commented on examples/api/src-tauri/gen/schemas/mobile-schema.json
seems like we have a misconfigured .gitignore, this file and directory shouldn't be commited

2024-09-16 13:22 UTC, amrbashir approved these changes

2024-09-16 13:56 UTC, FabianLars approved these changes

2024-09-16 14:01 UTC, merged