feat(updater): Add .deb Package Support to Linux Updater
tauri-apps/plugins-workspace pull request #1991
Opened 2024-11-01 03:12 UTC by jLynx

## Description

This PR extends the Linux updater functionality to support .deb package updates alongside the existing AppImage support. The implementation includes multiple authentication methods for package installation, providing a user-friendly update experience for Debian-based distributions.

_Note: This PR relies on https://github.com/tauri-apps/tauri/pull/11562_

### Key Features

- Support for both .deb packages and AppImage updates
- Multiple privilege escalation methods:

1. `pkexec` (primary, graphical)
2. `zenity` for GUI password prompt
3. Terminal-based `sudo` as fallback

- Automatic detection of installation type (AppImage vs .deb)
- Secure handling of authentication and package installation

### Technical Details

- Added new error types for authentication and installation failures
- Implemented .deb package extraction from both direct files and tar.gz archives
- Added helper methods for privilege escalation and authentication
- Maintained backward compatibility with existing AppImage functionality

### Expected Archive Structures

```javascript
├── [AppName]_[version]_amd64.AppImage.tar.gz
│   └──[AppName]_[version]_amd64.AppImage
├── [AppName]_[version]_amd64.deb
└── ...
```

## Testing

- Tested on Debian-based distributions
- Verified both .deb and AppImage update paths
- Tested various authentication scenarios

## Notes

- Requires `zenity` for graphical password prompt (optional)
- Falls back to terminal-based authentication if graphical methods fail
- Maintains security by properly handling sensitive authentication data

2024-11-03 21:31 UTC, jLynx commented
Removed support for .deb.tar.gz as requested by @FabianLars https://discord.com/channels/616186924390023171/1301285233991356506/1302596935101976616

2024-11-04 12:30 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +    }
how does that handle `rpm` or if installed within Arch Linux (through tools that convert .deb, or in the future when we add pacman support to tauri-bundler)?

2024-11-04 12:30 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +    }
I am also not sure why we would want to add support for `.deb` in the updater when the system itself has a package manager that can do the updates.

I think I prefer to notify the user there is an update and let them update through apt, or whatever other package manager for `.rpm`

2024-11-04 18:43 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    }
@amrbashir Thank you for the feedback! Let me address your points:

1. Regarding RPM and Arch Linux packages: You're right that this implementation is currently .deb specific. The intention was to start with .deb support as a first step as for our use case this is what we currently need.
2. About using system package managers: I understand your perspective about letting the system package manager handle updates. However, there are some use cases where direct .deb installation might be preferred:

- When the app isn't distributed through official repositories
- For organizations that want to control their own update distribution
- For testing/beta versions that aren't in package repositories

At the end of the day, the developer can choose to use this update mechanism or the package manager, it's just giving them another option. This implementation now brings Linux .deb packages in sync with other operating systems that support in-app updates. (Mac & Windows)

We personally couldn't use AppImages (which already support updates) in our project because they don't support deeplinks or icons, which .deb packages handle natively. This makes .deb packages a better choice for applications that need these features.

2024-11-12 00:36 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +    }
cool, I am convinced we should add support for .deb and potentially other formats like RPM and future pacman, but we need to fix the implementation to be 100% it is running from `.deb`

2024-11-12 00:41 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    }
Great news, Do you have any suggestions @amrbashir for how we could detect that?

2024-11-12 00:57 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    }
Would you be ok with this?
Consider it a deb package only if:
1. We're in a system path AND
2. We have Debian package management tools AND
3. The binary is tracked by dpkg

2024-11-12 01:03 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +    }
yeah that sounds good

2024-11-12 01:32 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    }
Have now updated that detection method @amrbashir

2024-11-12 01:53 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    }
Just fixed the linting, sorry about that @amrbashir

2024-11-12 02:11 UTC, amrbashir requested changes

2024-11-12 02:11 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +    fn install_appimage_update(&self, bytes: &[u8]) -> Result<()> {
```suggestion
    fn install_appimage(&self, bytes: &[u8]) -> Result<()> {
```

2024-11-12 02:11 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +    fn install_deb_update(&self, bytes: &[u8]) -> Result<()> {
```suggestion
    fn install_deb(&self, bytes: &[u8]) -> Result<()> {
```

2024-11-12 02:11 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +        if self.is_deb_package() {
we also need to check if `bytes` are actually for `.deb` see https://docs.rs/infer/latest/infer/archive/fn.is_deb.html

2024-11-12 02:11 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +            .tempdir_in("/tmp")?;
when doing app images, we actually try in 3 different temp locations, see L779-L783, we should do the same here

2024-11-12 02:11 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +        let _ = std::fs::remove_file(&deb_path);
this will be done automatically by tempfile crate, no?

2024-11-12 02:11 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +            .status()?;
won't `sudo` block and wait to type a password? which won't work for a GUI app since they are not necessarily started from a terminal?

2024-11-12 02:12 UTC, amrbashir reviewed
you also need to add a change file in .changes directory

2024-11-12 02:24 UTC, jLynx commented on plugins/updater/src/updater.rs
> +            .status()?;
It still prompts for password, here is a screenshot of it in progress. This was opened from the app selector on Ubuntu
![image](https://github.com/user-attachments/assets/4fcc744e-0605-4341-acab-0aae414e7e7e)

2024-11-12 02:36 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +            .status()?;
I see, but I remember some Desktop Enivornments might not have this behavior, anyways, let's ship and see really world usage.

2024-11-12 02:37 UTC, amrbashir requested changes

2024-11-12 02:37 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +        let output = std::process::Command::new("zenity")
what if `zenity` doesn't exist, I am not sure if all desktop environments have similar things but I think KDE has `kdialog`

2024-11-12 02:40 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        let output = std::process::Command::new("zenity")
If it doesnt exist, then it falls back to the other options, so having zenity installed it 100% optional on the users side and not required by any means

2024-11-12 02:42 UTC, jLynx commented
Will jump on your requested changes tomorrow morning as its EOD for me (NZ Timezone)

2024-11-12 02:48 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +        let output = std::process::Command::new("zenity")
then should we add support for `kdialog` as well, maybe as another fallback for KDE?

2024-11-12 22:06 UTC, jLynx commented on plugins/updater/src/updater.rs
> +            .tempdir_in("/tmp")?;
Do you want to use the same locations as appimage, or should I use 
`let tmp_dir_locations = ["/tmp", "/var/tmp", "/dev/shm"];`

2024-11-12 22:06 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        let _ = std::fs::remove_file(&deb_path);
very true, I'll remove this line

2024-11-12 22:13 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    fn install_deb_update(&self, bytes: &[u8]) -> Result<()> {
Updated. Will let you resolve if you are happy

2024-11-12 22:13 UTC, jLynx commented on plugins/updater/src/updater.rs
> +    fn install_appimage_update(&self, bytes: &[u8]) -> Result<()> {
Updated. Will let you resolve if you are happy

2024-11-12 22:14 UTC, jLynx commented on plugins/updater/src/updater.rs
> +            .tempdir_in("/tmp")?;
I have pushed the change with this, let me know if you want me to change it

2024-11-12 22:20 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        let _ = std::fs::remove_file(&deb_path);
Updated. Will let you resolve if you are happy

2024-11-12 22:25 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        let output = std::process::Command::new("zenity")
Added support for kdialog as well

2024-11-12 22:30 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        if self.is_deb_package() {
Good call, have now added this in

2024-11-12 22:31 UTC, jLynx commented
Ok, I think I have addressed all the comments here 😄

2024-11-12 22:52 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +        installation_result
```suggestion
        self.try_install_with_privileges(&deb_path)
```

2024-11-12 22:52 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +            .tempdir_in("/tmp")?;
I would prefer to use the same implementation as appimage

2024-11-12 22:54 UTC, amrbashir commented on .changes/deb-update-support.md
> +Added support for .deb package updates on Linux systems, including new error types (TempDirNotFound, AuthenticationFailed, DebInstallFailed) and implementation of .deb package installation with privi
```suggestion
Added support for `.deb` package updates on Linux systems.
```

2024-11-12 23:07 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        installation_result
Updated

2024-11-12 23:07 UTC, jLynx commented on .changes/deb-update-support.md
> +Added support for .deb package updates on Linux systems, including new error types (TempDirNotFound, AuthenticationFailed, DebInstallFailed) and implementation of .deb package installation with privi
Updated

2024-11-12 23:23 UTC, amrbashir commented on plugins/updater/src/updater.rs
> +        std::fs::write(&deb_path, bytes)?;
`std::fs::write` could fail and in which case we want to try the next temp dir location, let's change this to a for loop, similar to appimage implementaion

2024-11-12 23:27 UTC, amrbashir reviewed
I almost forgot, we have a test for each updater format in https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/updater/tests/app-updater/tests/update.rs could you also include .deb in that test as well?

2024-11-13 00:26 UTC, jLynx commented on plugins/updater/src/updater.rs
> +        std::fs::write(&deb_path, bytes)?;
Ok fair point. Have updated it to be inline with the appimage implementation

2024-11-13 00:50 UTC, jLynx commented
@amrbashir sent you a DM on discord, just around the testing stuff

2024-11-13 01:50 UTC, amrbashir commented on plugins/updater/tests/app-updater/tests/update.rs
> +        }
you can keep this one as is it was before

2024-11-13 01:50 UTC, amrbashir commented on plugins/updater/tests/app-updater/tests/update.rs
> +    }
we need to test both formats, not one or the other

2024-11-13 03:05 UTC, jLynx commented on plugins/updater/tests/app-updater/tests/update.rs
> +    }
Updated

2024-11-13 03:05 UTC, jLynx commented on plugins/updater/tests/app-updater/tests/update.rs
> +        }
Updated

2024-11-14 16:28 UTC, amrbashir commented on .github/workflows/integration-tests.yml
> +      # - name: install stable
why this was removed and now manually installing?

2024-11-14 16:28 UTC, amrbashir commented on plugins/updater/tests/app-updater/tests/update.rs
> +        return Self::Deb;
default in this test should stay AppImage

2024-11-14 19:00 UTC, jLynx commented on .github/workflows/integration-tests.yml
> +      # - name: install stable
This was for testing the pipeline as it doesnt work with sudo as it needs to be installed with sudo to work. will DM you

2024-11-24 00:42 UTC, amrbashir commented
@jLynx let's revert the updater test changes, I will merge the PR and add the test later in #2060 once I figure how to get MSI test to pass

2024-11-24 18:37 UTC, jLynx commented
ok cool, I will jump onto this in the next couple of hours

2024-11-24 21:06 UTC, jLynx commented
Removed the tests, so should be good to go @amrbashir

2024-11-24 23:41 UTC, jLynx commented
Fixed the formatting @amrbashir

2024-11-26 11:48 UTC, amrbashir approved these changes

2024-11-26 11:48 UTC, merged