Add support for HTTP Streaming
tauri-apps/plugins-workspace pull request #2140
Opened 2024-12-04 21:28 UTC by robertlong

This PR changes the internals of the fetch implementation such that `fetch_read_body` uses the `Channel` API to stream http responses instead of waiting for the entire response to finish and then returning the final ArrayBuffer.

Two things to note:

1. The `Channel<&[u8]>` type is serializing as a `number[]` instead of `ArrayBuffer` or `Uint8Array`. I'm not certain that the Channel supports serializing as `ArrayBuffer`s? I think this could be a possible performance improvement.

2. The `Channel` API implementation does not guarantee that all events are received by the time the `invoke` promise is resolved. This is unfortunate, but I worked around it by returning an empty array over the `Channel` which is used to close the `ReadableStream`. I think this design works alright, but maybe there's a cleaner way to do this.

Fixes https://github.com/tauri-apps/plugins-workspace/issues/2129#

2024-12-08 23:13 UTC, amrbashir requested changes
Thank you, could you also add a change file in `.changes` directory?

2024-12-08 23:13 UTC, amrbashir commented on plugins/http/guest-js/index.ts
> +        console.error('error reading body', e)
do we really need to console.error here? won't controller.error be enough?

2024-12-08 23:13 UTC, amrbashir commented on plugins/http/src/commands.rs
> +    let mut stream = res.bytes_stream();
can't we do the same streaming behavior using `Response::chunk` method, instead of pulling another crate to iterate over the stream?

2025-03-01 14:26 UTC, FabianLars commented
positive results on discord: https://discord.com/channels/616186924390023171/1344666371316908063 (not rushing anyone, i still think the review comments need to be acknowledged)

2025-03-02 11:29 UTC, mobilexiang commented
hello, is there any progress on this PR? Waiting for it to enable LLM streaming

2025-03-02 11:49 UTC, FabianLars commented
still waiting on reactions to the review comments 🤷

2025-03-08 18:45 UTC, closed without merging