feat(updater): refactor and improvemnts
tauri-apps/plugins-workspace pull request #431
Opened 2023-06-10 00:33 UTC by amrbashir

2023-06-17 22:18 UTC, lucasfernog requested changes

2023-06-17 22:18 UTC, lucasfernog commented on plugins/updater/src/lib.rs
> -pub struct Builder {
We shouldn't remove the Builder here.. installer_args is needed (even the integration test will fail without it IIRC) and a custom target option is nice to support custom configurations (for instance universal macOS bundles, different update channels..)

2023-06-19 12:40 UTC, amrbashir commented on plugins/updater/src/lib.rs
> -pub struct Builder {
sure yeah, I will provide both options

2023-06-20 00:00 UTC, lucasfernog requested changes

2023-06-20 00:00 UTC, lucasfernog commented on plugins/updater/guest-js/index.ts
> +/** Check for updates, returns `null` if no updates are available */
```suggestion
/** Check for updates, resolves to `null` if no updates are available */
```

2023-06-20 00:00 UTC, lucasfernog commented on plugins/updater/src/commands.rs
> +    headers: Option<Vec<(String, String)>>,
You changed the headers format without changing it in the TS API.

I prefer the object way btw, it's closer to other JS libraries like `fetch`, `axios`.

2023-06-20 00:00 UTC, lucasfernog commented on plugins/updater/src/lib.rs
> +pub fn init<R: Runtime>() -> TauriPlugin<R, Config> {
So far we never exposed an init function when we have a Builder.. I feel it hides that API and could confuse the user IMO.

2023-06-20 00:03 UTC, lucasfernog commented on plugins/updater/src/lib.rs
> +pub fn init<R: Runtime>() -> TauriPlugin<R, Config> {
Pushed a change to remove it.

2023-06-20 00:04 UTC, lucasfernog commented on plugins/updater/src/commands.rs
> +    headers: Option<Vec<(String, String)>>,
Pushed a commit to revert this.

2023-06-20 12:08 UTC, amrbashir commented on plugins/updater/src/commands.rs
> +    headers: Option<Vec<(String, String)>>,
Yeah my bad I was working on the http in parallel and mixed up. The JS api should definitely be an object like maybe even use [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) as fetch?

2023-06-20 12:12 UTC, amrbashir commented on plugins/updater/src/lib.rs
> +pub fn init<R: Runtime>() -> TauriPlugin<R, Config> {
I feel like most users won't configure the plugin and just plug it and forget about it and the init function has a nicer syntax that I don't really think we should give that up.

2023-06-20 20:14 UTC, lucasfernog commented on plugins/updater/src/commands.rs
> +    headers: Option<Vec<(String, String)>>,
I believe it already supports both a plain object and a Headers instance (which is nice).

2023-06-21 01:39 UTC, amrbashir commented on plugins/updater/src/commands.rs
> +    headers: Option<Vec<(String, String)>>,
Our definition of it is `Record<string, unknown>` while fetch `headers` filed is typed `[string, string][] | Record<string, string> | Headers`

2023-08-07 18:58 UTC, lucasfernog approved these changes

2023-08-07 19:01 UTC, merged