Proper MySQL examples and syntax explanation
tauri-apps/plugins-workspace pull request #499
Opened 2023-07-14 17:47 UTC by writeDavid

2023-07-14 18:24 UTC, FabianLars requested changes
Thank you! Great contribution :)

Apart from the 2 missing `"`, could you also turn the titles into code comments (`//`) so that the syntax highlighting keeps working?

2023-07-14 18:24 UTC, FabianLars commented on plugins/sql/README.md
> +        "INSERT into todos (id, title, status) VALUES ($1, $2, $3),
```suggestion
        "INSERT into todos (id, title, status) VALUES ($1, $2, $3)",
```

2023-07-14 18:24 UTC, FabianLars commented on plugins/sql/README.md
> +        "INSERT into todos (id, title, status) VALUES (?, ?, ?),
```suggestion
        "INSERT into todos (id, title, status) VALUES (?, ?, ?)",
```

2023-07-14 18:42 UTC, writeDavid commented
For the // conversion, do you want me to do that in both the index.ts and readme? 

MySQL is working flawlessly after figuring this out haha.  I was very confused at first.

2023-07-14 18:43 UTC, FabianLars commented
Yes please. Just to be sure cause i don't know how all editors would render that code comment otherwise

2023-07-14 19:02 UTC, FabianLars approved these changes, later dismissed

2023-07-14 19:03 UTC, FabianLars commented
can you run `pnpm format` real quick too?

2023-07-14 19:24 UTC, writeDavid commented
Okay. Ran that and pushed the updated file. 3rd times the charm??

2023-07-14 19:32 UTC, FabianLars commented
wait, it checks the syntax in readme files but can't update them? 😕

2023-07-14 20:45 UTC, writeDavid commented
I don't see any issues using pnpm format or format-check. I don't have a ton of prettier experience, so I don't know how to proceed.

2023-07-15 17:32 UTC, FabianLars submitted a review, later dismissed
thanks again!

2023-07-15 17:33 UTC, FabianLars commented
Or maybe not just yet 😂 The last commit wasn't signed so github doesn't allow me to merge the pr.

2023-07-16 20:05 UTC, closed without merging