feat(windwo-state): add group function
tauri-apps/plugins-workspace pull request #531
Opened 2023-08-03 05:55 UTC by a1156883061

https://github.com/tauri-apps/plugins-workspace/issues/507
Add group function.
If developer add a group, while label match the rule, it save window state to group name, else save to label name like previous logic.

2023-08-07 23:50 UTC, amrbashir requested changes
Thanks for your patience but I am quite busy with something else atm and can't focus on reviewing PRs right now but I took a quick look and I don't think we should go with the approach you proposed, instead I think we could maybe use a converter function, for example:
```rs
tauri_plugin_window_state::Builder::new()
	.transform_label(|label| {
		if label.startsWith("reader") {
			"reader".to_string()
		} else {
			label
		}	
	})
	.build()
```
but I will cc @lucasfernog, maybe he has a better idea

2023-08-08 14:09 UTC, lucasfernog commented
I like @amrbashir idea, it's easier to implement and use.

2023-08-10 03:41 UTC, a1156883061 commented
can you give me more specific reason why add_group is not a good approach. I think it more intuitive than transform_label.

2023-08-10 12:05 UTC, amrbashir commented
Your implementation is more complex, requires more allocations and usage of more mutexes while the proposed solution could just be a simple mapping function that probably will use zero-allocations.

I admit that `transform_label` is not very expressive and could use a better name though so I'd be happy to change that to a better name

2024-04-15 15:51 UTC, closed without merging

2024-04-15 15:51 UTC, FabianLars commented
I'm in the process of fixing the open v1 PRs according to provided feedback myself to finally be able to change the default branch to v2. I have troubles with this PR though, i believe we need to hear about more users' use cases to come up with a good PR because for me #507 is not enough. I just don't see the value here, or rather, how this actually solves problems.

Therefore i am closing this PR to unblock the v1 to v2 migration. Thank you for contributing nonetheless!