fix(updater): installation on macos #591
tauri-apps/plugins-workspace pull request #592
Opened 2023-09-05 12:29 UTC by pashokitsme

Using flate2 to decompressing tar.gz

2023-09-05 14:16 UTC, amrbashir requested changes
cc @lucasfernog since I can't test this

2023-09-05 14:16 UTC, amrbashir commented on plugins/updater/Cargo.toml
> +flate2 = "1.0.27"
the `zip` crate has `flate2` feature, could we use that instead of adding a new dependencies entry?

2023-09-05 15:27 UTC, pashokitsme commented on plugins/updater/Cargo.toml
> +flate2 = "1.0.27"
Sure
I didn't notice zip has such feature

2023-10-13 17:43 UTC, FabianLars commented
Since this PR was just mentioned in the other issue? Isn't it enough to literally just enable the feature in the zip crate? at a glance it looks like that's the only difference between the code in the plugin and the one in tauri v1 🤔

2023-10-13 18:47 UTC, pashokitsme commented
Updater for macos uses `.tar.gz` archives, so they unpacks with crate `tar` which only reads archives, not decompresses. In Tauri v1 [updater](https://github.com/tauri-apps/tauri/blob/1.3/core/tauri/src/updater/core.rs#L846) uses [ArchiveFormat & ArchiveReader](https://github.com/tauri-apps/tauri/blob/1.3/core/tauri/src/api/file/extract.rs#L18) which handles zip and tar archives and requires `flate2` under the hood

2023-10-13 18:53 UTC, FabianLars commented
Ah lol right, I forgot about our custom implementation, sorry!

2023-10-19 22:49 UTC, lucasfernog approved these changes

2023-10-19 22:50 UTC, merged