feat (log): Custom .log file names
tauri-apps/plugins-workspace pull request #633
Opened 2023-10-04 11:38 UTC by mellobacon

Addresses #122 and added appropriate docs. 

Probably should have error checking for the file name but just checking if the implementation is good for now.

2023-10-04 11:54 UTC, FabianLars commented
> Probably should have error checking for the file name but just checking if the implementation is good for now.

I think it makes sense to rename the app_name var to log_name to make the intention more clear. Maybe also merge the if into the let declaration so it doesn't even request the app name when there's a custom name, also would get rid of the mutability.

It looks good otherwise. And i'm not sure if we even have to validate it since that's something we generally don't really do with paths/file names 🤔

2023-10-04 11:54 UTC, FabianLars commented
Oh and thanks for contributing of course!!

2023-10-04 12:08 UTC, mellobacon commented
> I think it makes sense to rename the app_name var to log_name to make the intention more clear. Maybe also merge the if into the let declaration so it doesn't even request the app name when there's a custom name, also would get rid of the mutability.

Will do!
> Oh and thanks for contributing of course!!

And no problem :)

2023-10-04 12:36 UTC, FabianLars commented
Ah one last thing i overlooked (besides the format check failing) is to use an [Option](https://doc.rust-lang.org/std/option/index.html) instead of an empty string.
For what it's worth, this would also enable users to name their log file just `.log` if they want to.

2023-10-05 02:44 UTC, mellobacon commented
Let me know if there's anything else I missed 😅

2023-10-05 13:16 UTC, FabianLars requested changes
Just some small things left because i'm so picky lol (sorry) - meant to push this directly but didn't have access 🤷

2023-10-05 13:16 UTC, FabianLars commented on plugins/log/src/lib.rs
> +            log_name,
```suggestion
        Self {
            dispatch,
            rotation_strategy: DEFAULT_ROTATION_STRATEGY,
            timezone_strategy: DEFAULT_TIMEZONE_STRATEGY,
            max_file_size: DEFAULT_MAX_FILE_SIZE,
            targets: DEFAULT_LOG_TARGETS.into(),
            log_name: None,
```

2023-10-05 13:16 UTC, FabianLars commented on plugins/log/src/lib.rs
> +    pub fn log_name(mut self, log_name: &str) -> Self {
```suggestion
    pub fn log_name<S: Into<String>>(mut self, log_name: S) -> Self {
```

2023-10-05 13:16 UTC, FabianLars commented on plugins/log/src/lib.rs
> +                let log_name = name.as_str();
```suggestion
                let log_name = self
                    .log_name
                    .as_deref()
                    .unwrap_or_else(|| &app_handle.package_info().name);
```

2023-10-05 13:18 UTC, FabianLars commented on plugins/log/src/lib.rs
> +        self.log_name = Some(log_name.to_string());
```suggestion
        self.log_name = Some(log_name.into());
```

2023-10-05 13:19 UTC, FabianLars approved these changes
thank youuu

2023-10-05 13:24 UTC, merged