fix(single-instance): the incorrect type of dbus_id in linux arch
tauri-apps/plugins-workspace pull request #792
Opened 2023-12-03 11:01 UTC by yetone

fix https://github.com/tauri-apps/plugins-workspace/issues/791

2023-12-04 10:52 UTC, FabianLars requested changes
Thank you! Just one small question (see the other comment). Also, could you please add a changefile similar to https://github.com/tauri-apps/plugins-workspace/blob/v2/.changes/fix-permission-notification.md ?

2023-12-04 10:52 UTC, FabianLars commented on plugins/single-instance/src/platform_impl/linux.rs
> +        let dbus_name = format!("org.{}.SingleInstance", dbus_id(&manager.config()));
This `&` shouldn't be necessary, right? (Since config() already returns `&Config`)
Same for line 38.

2023-12-04 12:02 UTC, yetone commented
‌‌‌‌All have been repaired.

2023-12-04 12:27 UTC, yetone commented
‌‌Oops, maybe I should change it back?

https://github.com/tauri-apps/plugins-workspace/actions/runs/7086070602/job/19284953478?pr=792#step:7:14

2023-12-04 12:33 UTC, FabianLars commented
Thank you! Another thing i missed is that i can only merge this PR if all commits are signed. If you could set this up it's ready to go (here's a guide: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification - i recommend the ssh approach because i think it's easier. A guide for gpg is right above that though)

> ‌‌Oops, maybe I should change it back?

Ahh, my bad. The `config()` function was changed in alpha.18, the repo & lockfile is still on alpha.17. I imagine that other plugins will also break when changing that.

2023-12-04 12:39 UTC, FabianLars commented
Okay looks like all the other plugins still work after upgrading (at least locally)

2023-12-05 15:51 UTC, yetone commented
‌‌‌‌‌‌ My commits are already signed.

2023-12-11 20:15 UTC, amrbashir approved these changes

2023-12-11 21:39 UTC, FabianLars commented
Well, this was fixed in another commit, sorry about that :/

2023-12-11 21:39 UTC, closed without merging