type: add OpenDialogReturn generic type
tauri-apps/plugins-workspace pull request #919
Opened 2024-01-27 02:48 UTC by iShibi

Add generic type `OpenDialogReturn` to conditionally define the return type of the `open` function. It replaces multiple declarations of the `open` function.

2024-01-29 13:00 UTC, amrbashir commented
Is there any benefits over function overloading?

2024-01-29 23:18 UTC, iShibi commented
> Is there any benefits over function overloading?
> 
> Also you need to run `pnpm format` in the repo root

Conditional Types are preferred over Function Overloading. https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

2024-01-29 23:42 UTC, FabianLars commented
is it just me or is the variant based function overloading much easier to read and understand (both in this PR and in the example in your screenshot)?

2024-01-29 23:48 UTC, amrbashir requested changes
I agree with @FabianLars that overloading is easier to read but given that the docs will contain [multiple definitions](https://beta.tauri.app/references/v2/js/dialog/#open), I will go with this generic type solution

2024-01-29 23:48 UTC, amrbashir commented on plugins/dialog/guest-js/index.ts
> +type OpenDialogReturn<T extends OpenDialogOptions> = T["directory"] extends true
We need to export this type as well.

2024-01-30 00:07 UTC, amrbashir approved these changes

2024-01-30 00:08 UTC, merged