upgrade to iota_stronghold 2.0.0
tauri-apps/plugins-workspace pull request #950
Opened 2024-02-14 01:23 UTC by andrewweston

As discussed with @FabianLars, I have upgraded `iota_stronghold` to v2.0.0. The plugin compiles (the sql plugin is preventing a clean build) and works in my test app

2024-02-14 11:39 UTC, FabianLars requested changes
awesome, thank you :)

2024-02-14 11:39 UTC, FabianLars commented on plugins/stronghold/Cargo.toml
> +iota_stronghold = "2.0.0"
```suggestion
iota_stronghold = "2"
```
just to make renovate less annoying lol

2024-02-14 11:39 UTC, FabianLars commented on plugins/stronghold/Cargo.toml
> +rust-argon2 = { version = "2.1.0", optional = true }
```suggestion
rust-argon2 = { version = "2", optional = true }
```
same

2024-02-23 21:57 UTC, andrewweston commented
Apologies for the delay in getting back to this, I had a busier week than I was expecting. It looks like you may have already made the changes?

2024-02-24 13:34 UTC, FabianLars approved these changes

2024-02-27 01:00 UTC, closed without merging