refactor!(global-shortcut): better APIs DX
tauri-apps/plugins-workspace pull request #969
Opened 2024-02-19 16:28 UTC by amrbashir

ref: https://github.com/tauri-apps/plugins-workspace/issues/965

2024-02-19 19:10 UTC, simonhyll requested changes

2024-02-19 19:10 UTC, simonhyll commented on .changes/global-shortcut-refactor.md
> +- Add `GlobalShortcutExt::register_wihtout_handler` and `GlobalShortcutExt::register_all_wihtout_handler` that work the same as old APIs (i.e. register without a handler).
```suggestion
- Add `GlobalShortcutExt::register_without_handler` and `GlobalShortcutExt::register_all_without_handler` that work the same as old APIs (i.e. register without a handler).
```

2024-02-20 13:35 UTC, lucasfernog commented
Do we reall need the without_handler variants? can't users just define an empty closure and then the global listener handles the event?

2024-02-20 15:38 UTC, amrbashir commented
I am not happy with it either, the idea is to provide a method to register a shortcut without handler that is appealing to use, without using an empty closure, but a long method name is not good either, maybe just call it `register2`?

2024-02-21 13:55 UTC, lucasfernog commented
maybe `register_without_handler` keeps its name `register` and the new API is named `on_shortcut`? so it's clear you intend on providing a callback there

2024-02-21 18:49 UTC, amrbashir commented
> maybe `register_without_handler` keeps its name `register` and the new API is named `on_shortcut`? so it's clear you intend on providing a callback there

I am afraid that might confuse users because `on_` methods throughout tauri, are used to register just the listener.

2024-02-21 19:31 UTC, amrbashir commented
Changed to take an `Option` instead

2024-02-21 20:47 UTC, lucasfernog commented
> > maybe `register_without_handler` keeps its name `register` and the new API is named `on_shortcut`? so it's clear you intend on providing a callback there
> 
> I am afraid that might confuse users because `on_` methods throughout tauri, are used to register just the listener.

that's what the on_ here will do:

```rust
fn on_shortcut(&self, shortcut: &str, handler: impl Fn()) {}
fn register(&self, shortcut: &str) {}
```

2024-02-21 20:58 UTC, amrbashir commented
maybe I am overthinking it, let's roll with that and see user feedback

2024-02-21 21:02 UTC, amrbashir commented
> that's what the on_ here will do:
> 
> ```rust
> fn on_shortcut(&self, shortcut: &str, handler: impl Fn()) {}
> fn register(&self, shortcut: &str) {}
> ```

hmm if we go with that approach, there will be inconsistencies between the JS and Rust APIs

2024-02-21 23:15 UTC, lucasfernog commented
it's already inconsistent though :joy: JS is just different.. right now i wish we had function overloading in rust :D

2024-02-22 16:38 UTC, amrbashir commented
Alright, added that along with a few methods on the `Builder` that should make it more Rusty hopefully.

2024-03-07 16:31 UTC, lucasfernog approved these changes

2024-03-07 16:33 UTC, merged