fix(upload): return type on POST is now string
tauri-apps/plugins-workspace pull request #976
Opened 2024-02-21 13:55 UTC by lyager

A POST to a webserver can not always be expected to be a JSON response.

Success is now determined by the HTTP return code.

Upon success the body content is returned as a string.

2024-02-21 13:56 UTC, lyager commented
This might be more of a suggestion - not all web services receiving a post returns JSON. Propose to leave result processing to the end-user

2024-02-28 21:54 UTC, FabianLars commented
Hmm, you're right with that, however we actually ignore the return value on the js side so we may as well return `Result<()>` from the command instead so we can get rid of both res.json() and res.text() and really only use the status.

For that status error i'd prefer if you could add a new Error enum variant instead of using ContentLength

Lastly, it would be much appreciated if you could apply the same to the download command after making those changes :)

P.S. Thank you for contributing!

2024-02-29 13:40 UTC, lyager commented
Thanks for the feedback @FabianLars I somehow missed your response. I'll give it another shot hopefully soon

2024-02-29 15:12 UTC, lyager commented
@FabianLars Ok, I think that was all of your suggestions :) What do you think?

2024-03-04 15:14 UTC, lyager commented
.. my default linter formater apperantly is different that `cargo fmt` - I fixed it. Sorry.

2024-03-11 20:48 UTC, lucasfernog commented on plugins/upload/src/lib.rs
> +    Err(Error::HttpErrorCode(response.status().as_u16()))
```suggestion
    if response.status().is_success() {
        response.text().await.map_err(Into::into)
    } else {
        Err(Error::HttpErrorCode(response.status().as_u16()))
    }
```

2024-03-12 09:26 UTC, FabianLars commented
There's still this part open from above:
> Hmm, you're right with that, however we actually ignore the return value on the js side so we may as well return Result<()> from the command instead so we can get rid of both res.json() and res.text() and really only use the status.

So if there's any value in the response body we'll also have to fix the js side to actually forward it to the user.

2024-03-14 10:41 UTC, lyager commented
@FabianLars You're right. It should be fixed now.

I also added @lucasfernog suggestion.

I'll do some extensive test, but I think this should finally be it 😅

2024-03-21 11:22 UTC, lucasfernog requested changes, later dismissed
We also need a change file (a markdown file under the .changes folder) like this:
```
---
"upload": patch
"upload-js": patch
---

Return the upload response as a string and error out if the status code is not within 200-299.
```

2024-03-21 11:22 UTC, lucasfernog commented on plugins/upload/src/lib.rs
> +    HttpErrorCode(u16),
```suggestion
    #[error("request failed with status code {0}: {1}")]
    HttpErrorCode(u16, String),
```

2024-03-21 11:22 UTC, lucasfernog commented on plugins/upload/src/lib.rs
> +        Err(Error::HttpErrorCode(response.status().as_u16()))
```suggestion
        Err(Error::HttpErrorCode(
            response.status().as_u16(),
            response.text().await.unwrap_or_default(),
        ))
```

2024-03-21 11:22 UTC, lucasfernog commented
Tried to push changes to your repo but i'm not allowed to :(

2024-03-21 12:08 UTC, lyager commented
@lucasfernog Thank you for your help, there are clearly some corners in the repo that are unknown to me. I've accepted you proposals in the Github UI.

2024-03-21 17:58 UTC, lucasfernog commented
@lyager please also push the change file i mentioned above :)

2024-03-25 12:11 UTC, lyager commented
Thanks for the patience @lucasfernog , I've rebased and added the covector file you mentioned.

2024-03-26 14:21 UTC, lucasfernog commented
idk why but the diff is crazy right now :( something went wrong with your rebase

2024-04-02 06:44 UTC, lyager commented
@lucasfernog I've rebased against v1, now only 3 files have changed.. Sorry about that, and thank you for your patience.

2024-04-15 13:14 UTC, FabianLars approved these changes

2024-04-15 13:16 UTC, merged