Improve `tauri-plugin-store` readme and code example
tauri-apps/plugins-workspace pull request #996
Opened 2024-02-25 16:53 UTC by Rigidity

This brings `tauri-plugin-store`'s readme up to date with the the latest v2 beta, improves the wording of a few things, and adds a note about preventing crashes while loading from the Rust side of things.

2024-02-27 16:19 UTC, amrbashir requested changes

2024-02-27 16:19 UTC, amrbashir commented on plugins/store/README.md
> +However, you can also load them manually later like so:
Stores are not loaded on creation but rather when using any method on it.

2024-02-27 16:19 UTC, amrbashir commented on plugins/store/README.md
> +```
We could probably skip this part, don't think it is that useful

2024-03-05 20:09 UTC, Rigidity commented
I'll finish this up today

2024-03-06 03:19 UTC, simonhyll commented
I'd say this is an improvement from a docs point of view and we have lots of users begging for better `store` docs. Imo we should merge this and potentially improve upon it later on, as long as the information is at least sufficiently accurate.

2024-03-06 03:20 UTC, simonhyll approved these changes

2024-03-06 04:08 UTC, amrbashir approved these changes

2024-03-06 04:08 UTC, merged